# Generated by Django 4.2.26 on 2025-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_games_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
